print("************************************************************************************************************************")
print("                                              HISTÓRIA MALUCA                                                           ")
print("************************************************************************************************************************")
print("------------------------------------------------------------------------------------------------------------------------")
print("                                                   AJUDA                                                                ")
print("Substantivo é a classe gramatical que denominam os seres. Além de objetos, pessoas e fenômenos.")
print("O substantivo comum é um tipo de substantivo que dá nome aos seres da mesma espécie (animais, plantas, objetos).")
print("Adjetivo é a palavra que expressa uma qualidade ou característica do ser.")
print("------------------------------------------------------------------------------------------------------------------------")

substantivo = input("Digite um substantivo comum (plural)\n")
substantivo_comum = input("Digite um subastativo comum\n")
jogo = input("Digite o nome de um jogo\n")
adjetivo = input("digite um adjetivo masculino\n")
substantivo_comum2 = input("Digite um substantivo comum masculino\n")
substantivo_comum3 = input("Digite um subastativo comum\n")
local = input("Digite o nome de um local\n")

print("Hoje eu acordei feliz. Eu abri minha janela")
print("para ver meu jardim, havia lá uma plantação de {} ".format(substantivo))
print("e eu gostava muito disso, foi por isso que plantei.")
print("Caminhei pra a cozinha e abri o  {} a procura de {} ".format(substantivo_comum, adjetivo))
print("eu queria muito comer isso, mas percebi que havia acabado.")
print("decidi, então, jogar um pouco de {} na sala de estar".format(jogo))
print("pois a sala de estar é o melhor lugar para jogar esse tipo de jogo")
print("Após jogar um pouco, eu havia me cansado e, então, decidi ligar a TV.")
print("Na televisão, estava passando o jornal")
print("A repórter disse algo {} e isso me fez ficar pasmo,".format(substantivo))
print("pois hoje era o dia do {} Eu odeio esse dia".format(substantivo_comum2))
print("Decidi terminar essa tarde vestindo minha roupa de {}".format(substantivo_comum3))
print("e fui para o meu {} ".format(local))